# Generated by Django 3.1.7 on 2021-06-20 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_delete_estilista'),
        ('users', '0002_auto_20210619_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_estilista',
            field=models.BooleanField(default=False, verbose_name='¿Estilista?'),
        ),
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal', verbose_name='Sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estilista',
                'verbose_name_plural': 'Estilistas',
                'permissions': [('es_estilista', 'Es estilista')],
            },
        ),
    ]
