# Generated by Django 3.1.7 on 2021-06-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210620_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_estilista',
        ),
    ]
