# Generated by Django 3.1.7 on 2021-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_estilista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilista',
            name='departure_time',
            field=models.TimeField(verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='estilista',
            name='entry_time',
            field=models.TimeField(verbose_name='Hora de entrada'),
        ),
    ]
