# Generated by Django 3.0.5 on 2021-02-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210211_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
