# Generated by Django 3.1.7 on 2021-06-20 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20210620_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicios', models.TimeField(verbose_name='Inicio del servicio')),
                ('hora_fins', models.TimeField(verbose_name='Fin del servicio')),
                ('orden_servicio', models.IntegerField(verbose_name='Orden de servicio')),
                ('estilista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.estilista', verbose_name='Estilista')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Dia de cita')),
                ('hora_inicio', models.TimeField(verbose_name='Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Fin')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total')),
                ('servicios', models.ManyToManyField(through='reservacion.DetalleReservacion', to='services.Servicio')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pago')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.reservacion', verbose_name='Reservacion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AddField(
            model_name='detallereservacion',
            name='reservacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservacion.reservacion', verbose_name='Reservación'),
        ),
        migrations.AddField(
            model_name='detallereservacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicio', verbose_name='Servicio'),
        ),
    ]
