# Generated by Django 4.0.1 on 2022-01-22 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallereservacion',
            options={'verbose_name': 'Servicio de la reservación', 'verbose_name_plural': 'Servicios de la reservación'},
        ),
        migrations.AlterField(
            model_name='detallereservacion',
            name='orden_servicio',
            field=models.IntegerField(default=1, verbose_name='Orden de servicio'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
