# Generated by Django 3.0.5 on 2021-02-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sucursal')),
                ('direction', models.CharField(max_length=200, verbose_name='Dirección')),
                ('status', models.BooleanField(verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estilista')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('entry_time', models.TimeField(verbose_name='Hora de entrada')),
                ('departure_time', models.TimeField(verbose_name='Hora de salida')),
                ('status', models.BooleanField(verbose_name='¿Activo?')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursal.Sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Estilista',
                'verbose_name_plural': 'Estilistas',
            },
        ),
    ]
