# Generated by Django 3.1.7 on 2021-06-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estilista',
        ),
    ]
